spring:
  profiles:
    active: test

---
server:
  port: 8210

spring:
  profiles:
    active: dev
  application:
    name: test-cloud-dev-2.0


---

spring:
  profiles:
    active: test
  application:
    name: test-cloud-test-2.0